server:
  port: 8081
  ssl:
    enabled: true
    key-store: classpath:order.jks
    key-password: 123456
    key-store-password: 123456
    trust-store: classpath:order.jks
    trust-store-password: 123456
    key-alias: order
    client-auth: need

spring:
  application:
    name: order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://localhost:8761/eureka/
    tls:
      enabled: ${server.ssl.enabled}
      key-store: ${server.ssl.key-store}
      key-password: ${server.ssl.key-password}
      key-store-password: ${server.ssl.key-store-password}
      trust-store: ${server.ssl.trust-store}
      trust-store-password: ${server.ssl.trust-store-password}
  instance:
    hostname: localhost
    secure-port-enabled: true
    non-secure-port-enabled: false
    status-page-url: https://${eureka.instance.hostname}:${server.port}/info
    health-check-url: https://${eureka.instance.hostname}:${server.port}/health
    home-page-url: https://${eureka.instance.hostname}:${server.port}/